### ISSUE TITLE
下界合金工具挖掘错误

### ISSUE THREAD

**Issue by Sz-Yuan** [JesKi13567/Modern-Multitools#1]
当下界工具拥有效率附魔并切换过剑“外观”后，对铲子类挖掘的方块失去效果，具体表现为切换过剑后挖掘沙子，沙砾，泥土等的速度和空手挖掘速度一致

**Comment by JesKi13567** [comment]
能否提供更详细的说明，比如数据包版本号及mc版本号，我使用 MC1.21.1 运行 jkmt1.1.1 无法复现

**Comment by Sz-Yuan** [comment]
数据包为1.1.1版本，mc为1.21版本

**Comment by Sz-Yuan** [comment]
https://github.com/user-attachments/assets/b23fb892-42f0-480d-90cf-c931f557d3a3
切换到镐子后出现挖掘铲子类方块无法应用工具

> 能否提供更详细的说明，比如数据包版本号及mc版本号，我使用 MC1.21.1 运行 jkmt1.1.1 无法复现

**Comment by Sz-Yuan** [comment]
> 能否提供更详细的说明，比如数据包版本号及mc版本号，我使用 MC1.21.1 运行 jkmt1.1.1 无法复现

好像是数据包冲突了，添加了急迫2+效率5合金镐秒破深板岩，禁用秒破深板岩数据包后正常了😂，https://modrinth.com/datapack/instaslate

**Comment by JesKi13567** [comment]
彳亍，我还想吐槽你为什么不用原版端试试。。
